# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/anki_nb_deck_builder',
                'doc_host': 'https://Mees-Molenaar.github.io',
                'git_url': 'https://github.com/Mees-Molenaar/anki_nb_deck_builder',
                'lib_path': 'anki_nb_deck_builder'},
  'syms': {'anki_nb_deck_builder.core': {'anki_nb_deck_builder.core.foo': ('core.html#foo', 'anki_nb_deck_builder/core.py')}}}